//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int ID { get; set; }
        public Nullable<int> FromAccountNumber { get; set; }
        public Nullable<int> ToAccountNumber { get; set; }
        public string ToBankName { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
